// lib/restaurant-data.ts
import { Restaurant } from '@/app/types';

export const restaurants: Restaurant[] = [
  // ========== BALI ==========
  {
    id: 'rest-bali-locavore',
    name: 'Locavore Fine Dining Ubud',
    description: 'An extraordinary ingredient-driven dining concept highlighting 100% locally sourced Indonesian meats, greens, and spices.',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Modern Indonesian',
    priceLevel: '$$$',
    price: 130,
    rating: 4.9,
    reviewsCount: 56,
    location: 'Ubud, Bali, Indonesia',
    address: 'Jl. Dewisita No.10, Ubud, Bali',
    phone: '+62 361 981 123',
    hours: '12:00 – 23:00 daily',
    dietaryOptions: ['Vegetarian', 'Vegan', 'Gluten-Free'],
    destinationId: 'bali',
    coordinates: { lat: -8.5061, lng: 115.2629 },
    menuHighlights: ['Tasting Menu', 'Local Spices', 'Sustainable Seafood'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/locavore'
  },
  {
    id: 'rest-bali-nuri',
    name: "Naughty Nuri's Warung",
    description: 'A global landmark in Ubud famous for its smoky, sticky finger-licking pork ribs, stellar martinis, and high-energy vibe.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Indonesian BBQ',
    priceLevel: '$$',
    price: 35,
    rating: 4.7,
    reviewsCount: 88,
    location: 'Ubud, Bali, Indonesia',
    address: 'Jl. Raya Sanggingan, Ubud, Bali',
    phone: '+62 361 975 654',
    hours: '10:00 – 23:00 daily',
    dietaryOptions: ['Gluten-Free'],
    destinationId: 'bali',
    coordinates: { lat: -8.5061, lng: 115.2629 },
    menuHighlights: ['Pork Ribs', 'Martinis', 'Sate Lilit'],
    bookable: false,
  },
  // ========== KYOTO ==========
  {
    id: 'rest-kyoto-kaiseki',
    name: 'Kikunoi Kaiseki',
    description: 'A legendary kaiseki restaurant in Kyoto’s Gion district, offering multi‑course seasonal meals in a traditional Japanese setting.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Traditional Kaiseki',
    priceLevel: '$$$$',
    price: 250,
    rating: 4.9,
    reviewsCount: 72,
    location: 'Gion, Kyoto, Japan',
    address: '570-120 Gionmachi Minamigawa, Higashiyama-ku, Kyoto',
    phone: '+81 75-561-0015',
    hours: '12:00 – 14:00, 17:00 – 21:00',
    dietaryOptions: ['Vegetarian', 'Vegan', 'Gluten-Free'],
    destinationId: 'kyoto',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    menuHighlights: ['Seasonal Kaiseki', 'Sashimi', 'Wagyu Beef'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/kikunoi'
  },
  {
    id: 'rest-kyoto-ramen',
    name: 'Ichiran Ramen Kyoto',
    description: 'Famous tonkotsu ramen with customizable broth and noodles, served in iconic solo booths.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Ramen',
    priceLevel: '$',
    price: 12,
    rating: 4.5,
    reviewsCount: 230,
    location: 'Kyoto, Japan',
    address: 'Nakagyo-ku, Kyoto',
    phone: '+81 75-221-1234',
    hours: '24/7',
    dietaryOptions: ['Vegetarian (upon request)'],
    destinationId: 'kyoto',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    menuHighlights: ['Tonkotsu Ramen', 'Spicy Miso', 'Chashu'],
    bookable: false,
  },
  // ========== SANTORINI ==========
  {
    id: 'rest-santorini-oia',
    name: 'La Maison d\'Oia',
    description: 'A cliffside fine dining restaurant with breathtaking caldera views, serving modern Greek cuisine with a French twist.',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Modern Greek',
    priceLevel: '$$$',
    price: 95,
    rating: 4.8,
    reviewsCount: 43,
    location: 'Oia, Santorini, Greece',
    address: 'Oia, Santorini 84702, Greece',
    phone: '+30 22860 71410',
    hours: '19:00 – 00:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'santorini',
    coordinates: { lat: 36.4629, lng: 25.3752 },
    menuHighlights: ['Lobster Pasta', 'Feta Mousse', 'Santorini Tomato Fritters'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/oia'
  },
  {
    id: 'rest-santorini-fira',
    name: 'Argo Restaurant',
    description: 'A classic Greek taverna in Fira with a panoramic terrace, serving fresh seafood and traditional Greek dishes.',
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Greek Seafood',
    priceLevel: '$$',
    price: 50,
    rating: 4.6,
    reviewsCount: 78,
    location: 'Fira, Santorini, Greece',
    address: 'Fira, Santorini 84700, Greece',
    phone: '+30 22860 22442',
    hours: '12:00 – 00:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'santorini',
    coordinates: { lat: 36.4204, lng: 25.4310 },
    menuHighlights: ['Grilled Octopus', 'Moussaka', 'Santorini Salad'],
    bookable: false,
  },
  // ========== AMALFI COAST ==========
  {
    id: 'rest-amalfi-positano',
    name: 'La Sponda',
    description: 'A Michelin-starred restaurant in Positano, offering romantic candlelit dining with stunning sea views and modern Italian cuisine.',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Modern Italian',
    priceLevel: '$$$$',
    price: 180,
    rating: 4.9,
    reviewsCount: 52,
    location: 'Positano, Amalfi Coast, Italy',
    address: 'Via Cristoforo Colombo, 30, 84017 Positano SA, Italy',
    phone: '+39 089 875 822',
    hours: '19:30 – 22:30',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'amalfi-coast',
    coordinates: { lat: 40.6281, lng: 14.4860 },
    menuHighlights: ['Lemon Tagliolini', 'Seared Scallops', 'Tiramisu'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/lasponda'
  },
  {
    id: 'rest-amalfi-ravello',
    name: 'Ristorante Rossellinis',
    description: 'A refined restaurant at the Belmond Hotel Caruso, perched on a Ravello cliff, serving authentic Campanian cuisine.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Campanian Italian',
    priceLevel: '$$$',
    price: 140,
    rating: 4.7,
    reviewsCount: 38,
    location: 'Ravello, Amalfi Coast, Italy',
    address: 'Piazza S. Giovanni del Toro, 2, 84010 Ravello SA, Italy',
    phone: '+39 089 858 801',
    hours: '12:30 – 14:30, 19:30 – 22:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'amalfi-coast',
    coordinates: { lat: 40.6490, lng: 14.6100 },
    menuHighlights: ['Paccheri with Lobster', 'Eggplant Parmigiana', 'Lemon Delight'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/rossellinis'
  },
  // ========== NEW YORK ==========
  {
    id: 'rest-ny-bernardin',
    name: 'Le Bernardin',
    description: 'Legendary 3-Star Michelin Seafood Temple by Eric Ripert, serving pristine seafood in a sophisticated setting.',
    image: 'https://images.pexels.com/photos/34964940/pexels-photo-34964940.jpeg',
    cuisine: 'Fine French Seafood',
    priceLevel: '$$$$',
    price: 220,
    rating: 4.9,
    reviewsCount: 120,
    location: 'New York, USA',
    address: '155 W 51st St, New York, NY 10019, USA',
    phone: '+1 212-554-1515',
    hours: 'Mon–Sat 12:00–14:30, 17:30–22:30',
    dietaryOptions: ['Kosher-style', 'Gluten-Free'],
    destinationId: 'new-york',
    coordinates: { lat: 40.7620, lng: -73.9808 },
    menuHighlights: ['Tuna Belly', 'Lobster Tail', 'Black Bass'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/bernardin'
  },
  {
    id: 'rest-ny-katz',
    name: "Katz's Delicatessen",
    description: 'Iconic Jewish deli in the Lower East Side serving hand-carved hot pastrami on rye since 1888.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Classic Kosher Deli',
    priceLevel: '$$',
    price: 25,
    rating: 4.7,
    reviewsCount: 280,
    location: 'New York, USA',
    address: '205 E Houston St, New York, NY 10002, USA',
    phone: '+1 212-254-2246',
    hours: '8:00 – 23:00 daily',
    dietaryOptions: ['Kosher'],
    destinationId: 'new-york',
    coordinates: { lat: 40.7221, lng: -73.9862 },
    menuHighlights: ['Pastrami on Rye', 'Matzo Ball Soup', 'Corned Beef'],
    bookable: false,
  },
  {
    id: 'rest-ny-bouley',
    name: 'Bouley at Home',
    description: 'A modern American restaurant in Tribeca with a focus on seasonal ingredients and artistic plating.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Contemporary American',
    priceLevel: '$$$',
    price: 120,
    rating: 4.8,
    reviewsCount: 65,
    location: 'New York, USA',
    address: '163 Duane St, New York, NY 10013, USA',
    phone: '+1 212-608-9200',
    hours: 'Mon–Sat 17:30–22:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'new-york',
    coordinates: { lat: 40.7171, lng: -74.0084 },
    menuHighlights: ['Foie Gras', 'Sea Bass', 'Chocolate Soufflé'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/bouley'
  },
  // ========== PARIS ==========
  {
    id: 'rest-paris-ambroisie',
    name: "L'Ambroisie",
    description: 'A three-Michelin-starred temple of classic French haute cuisine, located in a 17th-century townhouse on Place des Vosges.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Classic French Haute',
    priceLevel: '$$$$',
    price: 350,
    rating: 4.9,
    reviewsCount: 34,
    location: 'Paris, France',
    address: '9 Place des Vosges, 75004 Paris, France',
    phone: '+33 1 42 78 51 45',
    hours: 'Mon–Sat 12:00–14:30, 19:30–22:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'paris',
    coordinates: { lat: 48.8551, lng: 2.3658 },
    menuHighlights: ['Foie Gras', 'Roasted Pigeon', 'Grand Marnier Soufflé'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/ambroisie'
  },
  {
    id: 'rest-paris-creperie',
    name: 'Breizh Café Le Marais',
    description: 'Artisanal Breton buckwheat galettes with fine French cheeses, ham, and organic cider in a cozy Marais setting.',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Breton Galettes',
    priceLevel: '$',
    price: 20,
    rating: 4.7,
    reviewsCount: 92,
    location: 'Paris, France',
    address: '109 Rue Vieille du Temple, 75003 Paris, France',
    phone: '+33 1 42 72 13 77',
    hours: '12:00 – 22:00 daily',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'paris',
    coordinates: { lat: 48.8611, lng: 2.3624 },
    menuHighlights: ['Buckwheat Galette', 'Camembert', 'Breton Cider'],
    bookable: false,
  },
  {
    id: 'rest-paris-la-perouse',
    name: 'La Pérouse',
    description: 'An iconic Parisian brasserie since 1893, famous for its historic charm, mirrored dining rooms, and classic French seafood.',
    image: 'https://images.pexels.com/photos/16385739/pexels-photo-16385739.jpeg',
    cuisine: 'Classic French Brasseries',
    priceLevel: '$$$',
    price: 95,
    rating: 4.6,
    reviewsCount: 110,
    location: 'Paris, France',
    address: '51 Quai des Grands Augustins, 75006 Paris',
    phone: '+33 1 43 26 68 04',
    hours: '12:00 – 14:30, 19:00 – 22:30',
    dietaryOptions: ['Vegetarian', 'Seafood'],
    destinationId: 'paris',
    coordinates: { lat: 48.8546, lng: 2.3428 },
    menuHighlights: ['Oysters', 'Bouillabaisse', 'Steak Frites'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/laperouse'
  },
  // ========== TOKYO ==========
  {
    id: 'rest-tokyo-jiro',
    name: 'Sukiyabashi Jiro Roppongi',
    description: 'World-famous sushi omakase by master Jiro Ono’s son, with an intimate 10-seat counter experience.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Traditional Sushi',
    priceLevel: '$$$',
    price: 250,
    rating: 4.9,
    reviewsCount: 41,
    location: 'Tokyo, Japan',
    address: 'Roppongi Hills, Minato-ku, Tokyo',
    phone: '+81 3-3423-1234',
    hours: '11:30 – 14:00, 17:00 – 20:00',
    dietaryOptions: ['Gluten-Free'],
    destinationId: 'tokyo',
    coordinates: { lat: 35.6600, lng: 139.7295 },
    menuHighlights: ['Omakase Nigiri', 'Tuna', 'Eel'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/jiro'
  },
  {
    id: 'rest-tokyo-ichiran',
    name: 'Ichiran Ramen Shinjuku',
    description: 'The legendary tonkotsu ramen house with private booths, customizable spice, and rich pork bone broth.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Hakata Ramen',
    priceLevel: '$',
    price: 15,
    rating: 4.6,
    reviewsCount: 145,
    location: 'Shinjuku, Tokyo, Japan',
    address: 'Shinjuku 3-34-11, Shinjuku-ku, Tokyo',
    phone: '+81 3-3352-2451',
    hours: '24/7',
    dietaryOptions: ['Vegetarian (upon request)'],
    destinationId: 'tokyo',
    coordinates: { lat: 35.6895, lng: 139.6917 },
    menuHighlights: ['Tonkotsu Ramen', 'Spicy Miso', 'Chashu'],
    bookable: false,
  },
  {
    id: 'rest-tokyo-robot',
    name: 'Robot Restaurant',
    description: 'An over-the-top entertainment dining experience with neon lights, giant robots, and live performances – pure fun.',
    image: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Modern Japanese',
    priceLevel: '$$',
    price: 50,
    rating: 4.2,
    reviewsCount: 320,
    location: 'Shinjuku, Tokyo, Japan',
    address: '1-7-1 Kabukicho, Shinjuku-ku, Tokyo',
    phone: '+81 3-3200-1400',
    hours: '12:00 – 23:00',
    dietaryOptions: ['Vegetarian'],
    destinationId: 'tokyo',
    coordinates: { lat: 35.6940, lng: 139.7023 },
    menuHighlights: ['Sushi Platter', 'Takoyaki', 'Robot Show'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/robot'
  },
  // ========== LONDON ==========
  {
    id: 'rest-london-fatmango',
    name: 'Fat Mango by Ottolenghi',
    description: 'A vibrant restaurant serving inventive Middle Eastern and Mediterranean small plates, known for bold flavors and colorful ingredients.',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Middle Eastern / Mediterranean',
    priceLevel: '$$',
    price: 45,
    rating: 4.8,
    reviewsCount: 88,
    location: 'London, UK',
    address: '17-19 High Street, London SW6 1HQ',
    phone: '+44 20 7384 2121',
    hours: '12:00 – 22:00 daily',
    dietaryOptions: ['Vegetarian', 'Vegan', 'Gluten-Free'],
    destinationId: 'london',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    menuHighlights: ['Cauliflower Shawarma', 'Za’atar Fries', 'Labneh'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/fatmango'
  },
  {
    id: 'rest-london-rules',
    name: 'Rules Restaurant',
    description: 'The oldest restaurant in London (est. 1798), serving classic British game, oysters, and puddings in a historic setting.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Traditional British',
    priceLevel: '$$$',
    price: 70,
    rating: 4.6,
    reviewsCount: 65,
    location: 'London, UK',
    address: '35 Maiden Lane, Covent Garden, London WC2E 7LB',
    phone: '+44 20 7836 5314',
    hours: 'Mon–Sat 12:00–22:30, Sun 12:00–21:30',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'london',
    coordinates: { lat: 51.5110, lng: -0.1228 },
    menuHighlights: ['Roast Beef', 'Steak & Kidney Pie', 'Sticky Toffee Pudding'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/rules'
  },
  // ========== SWITZERLAND ==========
  {
    id: 'rest-swiss-vrony',
    name: "Chez Vrony St. Moritz",
    description: 'Rustic-chic 2,100m Alpine mountain lodge serving organic Swiss cheeses, dry-aged beef, and fondue with panoramic Matterhorn views.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Alpine Swiss',
    priceLevel: '$$$',
    price: 85,
    rating: 4.9,
    reviewsCount: 110,
    location: 'Zermatt / St. Moritz, Switzerland',
    address: '2,100m Alpine Ridge, Zermatt',
    phone: '+41 27 966 12 34',
    hours: 'Daily 09:30 – 16:00',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'switzerland',
    coordinates: { lat: 46.0207, lng: 7.7491 },
    menuHighlights: ['Fondue', 'Dry-aged Beef', 'Homemade Sausages'],
    bookable: true,
    bookingUrl: 'https://reservations.example.com/vrony'
  },
  {
    id: 'rest-swiss-grill',
    name: 'The Alpine Grill',
    description: 'A cozy mountain grill serving juicy steaks, grilled sausages, and traditional rösti with spectacular alpine views.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Swiss Grill',
    priceLevel: '$$',
    price: 40,
    rating: 4.5,
    reviewsCount: 45,
    location: 'Grindelwald, Switzerland',
    address: 'Kirchgasse 12, 3818 Grindelwald',
    phone: '+41 33 854 12 34',
    hours: '11:00 – 22:00 daily',
    dietaryOptions: ['Vegetarian', 'Gluten-Free'],
    destinationId: 'switzerland',
    coordinates: { lat: 46.6260, lng: 8.0355 },
    menuHighlights: ['Rösti', 'Veal Sausage', 'Apple Strudel'],
    bookable: false,
  },
  // ========== Add more from other places if needed ==========
];